### ISSUE TITLE
Fantastic extension but doesn't work?

### ISSUE THREAD

**Issue by EssamWisam** [mo-dhia/style-extractor#1]
This is exactly what I was looking for. However, I tried on the following example HTML and it didn't seem to work:
```html
<html>
<div class="container">
	<div class="headline"
		style="display: flex; cursor: pointer; flex-direction: column; justify-content: center; align-items: center; border-radius:3rem; margin-top: 1.5rem; padding: 1rem; width:100%; ">
		<h1
			class="title"
			style="margin: 1rem; font-family: 'Lato'; font-weight: 700; font-style: italic;  font-size: 2.4rem; text-align:center; width:80%">
			Hello <span class="purple-span" style="color:darkmagenta;">World</span> 
			<span class="purple-span" style="color:darkmagenta;"> Test</span>
		</h1>
	</div>

</html>
```
In particular, it gives me:
```css
.container { margin:  1rem;  font-family:  Lato;  font-weight:  700;  font-style:  italic;   font-size:  2.4rem;  text-align: center;  width: 80%; }
.headline { color: darkmagenta; }
.purple-span { color: darkmagenta; }
```
The title class was ignored and the container class should have received no styles.
